<?php

function eventos_menu() {

  $items = array();

  $items['admin/create/paciente'] = array( 
    'title' => 'Identifique o Paciente',
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('paciente_form'),
    'access arguments' => array('access content')
  );

  $items['calendar/getEventos'] = array(
    'delivery callback' => 'getEventos',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content')
  );

  $items['calendar/getEventosByProfissional'] = array(
    'delivery callback' => 'getEventosByProfissional',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content')
  );

  $items['calendar/alterEvento'] = array(
    'delivery callback' => 'alterEvento',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content')
  );
  
  $items['getProcedimentos'] = array(
    'delivery callback' => 'getProcedimentos',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content')
  );

  $items['getDadosProcedimentos'] = array(
    'delivery callback' => 'getDadosProcedimentos',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content')
  );

  $items['manipulaAgendamento'] = array(
    'delivery callback' => 'manipulaAgendamento',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content')
  );

  $items['getPagamentos'] = array(
    'delivery callback' => 'getPagamentos',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content')
  );

  $items['salvarProntuario'] = array(
    'delivery callback' => 'salvarProntuario',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content')
  );

  $items['getSaldo'] = array(
    'delivery callback' => 'getSaldo',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content')
  );

  $items['importProcedimento'] = array(
    'delivery callback' => 'importProcedimento',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content')
  );

  return $items;
  
}

function importProcedimento(){
  // $p = node_load(99);
  // debugFake($p);
  /*
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Aparelho de Contenção Final - Arcada Inferior";	$p->field_valor['und'][0]['value'] = 	100.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Aparelho de Contenção Final - Arcada Superior";	$p->field_valor['und'][0]['value'] = 	100.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Aparelho de Protrusão Mandibular/Bionator";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Aplicação de cariostático";	$p->field_valor['und'][0]['value'] = 	30.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Aplicação tópica de flúor";	$p->field_valor['und'][0]['value'] = 	15.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Aplicação tópica de verniz fluoretado";	$p->field_valor['und'][0]['value'] = 	30.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Arco Lingual ou Alça Banda";	$p->field_valor['und'][0]['value'] = 	100.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Arco ou Barra Palatina";	$p->field_valor['und'][0]['value'] = 	100.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Atividade educativa em odontologia para pais e/ou cuidadores de pacientes com necessidades especiais";	$p->field_valor['und'][0]['value'] = 	0.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Avaliação para receita/atestado";	$p->field_valor['und'][0]['value'] = 	55.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Colagem de fragmentos dentários";	$p->field_valor['und'][0]['value'] = 	43.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Conserto em prótese parcial removível (em consultório e em laboratório)";	$p->field_valor['und'][0]['value'] = 	190.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Conserto em prótese total (em consultório e em laboratório)";	$p->field_valor['und'][0]['value'] = 	190.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Consulta / Estomatologia odontológica";	$p->field_valor['und'][0]['value'] = 	60.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Consulta odontológica inicial";	$p->field_valor['und'][0]['value'] = 	60.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Controle de hemorragia com aplicação de agente hemostático em região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	43.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Controle de hemorragia sem aplicação de agente hemostático em região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	43.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Controle pós-operatório em odontologia";	$p->field_valor['und'][0]['value'] = 	0.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa provisória com pino (unitária)";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa provisória sem pino (unitária)";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa total metálica";	$p->field_valor['und'][0]['value'] = 	533.81;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Diagnóstico anatomopatológico em citologia esfoliativa na região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	250.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Diagnóstico anatomopatológico em material de biópsia na região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	250.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Diagnóstico anatomopatológico em peça cirúrgica na região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	250.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Diagnóstico anatomopatológico em punção na região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	250.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Diagnóstico e planejamento para tratamento odontológico";	$p->field_valor['und'][0]['value'] = 	0.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Disjuntor Palatino";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Elemento em metalocerâmica";	$p->field_valor['und'][0]['value'] = 	512.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Enxerto ósseo pré implante por elemento - COM MEMBRANA";	$p->field_valor['und'][0]['value'] = 	2000.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Enxerto ósseo pré implante por elemento - SEM MEMBRANA";	$p->field_valor['und'][0]['value'] = 	1500.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Exodontia com osteoctomia";	$p->field_valor['und'][0]['value'] = 	180.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Exodontia simples de decíduo";	$p->field_valor['und'][0]['value'] = 	75.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Faceta direta em resina fotopolimerizável";	$p->field_valor['und'][0]['value'] = 	200.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Faceta em cerâmica pura";	$p->field_valor['und'][0]['value'] = 	900.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Fechamento de diastema";	$p->field_valor['und'][0]['value'] = 	120.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Frenulectomia labial";	$p->field_valor['und'][0]['value'] = 	250.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Frenulectomia lingual";	$p->field_valor['und'][0]['value'] = 	250.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Frenulotomia labial";	$p->field_valor['und'][0]['value'] = 	200.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Frenulotomia lingual";	$p->field_valor['und'][0]['value'] = 	200.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Grade Palatina Fixa";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Grade Palatina Móvel";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Implante (fase cirúrgica)";	$p->field_valor['und'][0]['value'] = 	1000.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Incisão e drenagem extraoral de abscesso. hematoma e/ou flegmão da região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	120.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Incisão e drenagem intraoral de abscesso. hematoma e/ou flegmão da região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	120.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Instalação de aparelho Autoligado";	$p->field_valor['und'][0]['value'] = 	250.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Instalação de aparelho Estético";	$p->field_valor['und'][0]['value'] = 	400.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Instalação de aparelho Metálico";	$p->field_valor['und'][0]['value'] = 	69.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Mantenedor de Espaço Fixo ou Móvel";	$p->field_valor['und'][0]['value'] = 	80.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Manutenção de Aparelho Fixo Autoligado";	$p->field_valor['und'][0]['value'] = 	100.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Manutenção de Aparelho Fixo Estético";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Manutenção de Aparelho Fixo Metálico";	$p->field_valor['und'][0]['value'] = 	69.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Manutenção de Aparelho Móvel";	$p->field_valor['und'][0]['value'] = 	80.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Mentoneira";	$p->field_valor['und'][0]['value'] = 	100.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Microabrasão (Por dente) - 3 Sessões";	$p->field_valor['und'][0]['value'] = 	300.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Máscara Facial";	$p->field_valor['und'][0]['value'] = 	100.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Núcleo metálico fundido";	$p->field_valor['und'][0]['value'] = 	235.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Orientação de higiene bucal (técnica de escovação e bochecho com flúor)";	$p->field_valor['und'][0]['value'] = 	0.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Pino metalocerâmico para elemento";	$p->field_valor['und'][0]['value'] = 	47.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Plano Inclinado de Acrílico";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Profilaxia";	$p->field_valor['und'][0]['value'] = 	70.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese total";	$p->field_valor['und'][0]['value'] = 	600.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Pulpectomia";	$p->field_valor['und'][0]['value'] = 	43.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Quadri-Hélice";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Radiografia oclusal";	$p->field_valor['und'][0]['value'] = 	35.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Radiografia periapical";	$p->field_valor['und'][0]['value'] = 	20.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Recimentação de trabalhos protéticos";	$p->field_valor['und'][0]['value'] = 	120.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Redução simples de luxação de articulação têmporomandibular - ATM";	$p->field_valor['und'][0]['value'] = 	43.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Reembasamento de coroa provisória";	$p->field_valor['und'][0]['value'] = 	43.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Regularização de rebordo";	$p->field_valor['und'][0]['value'] = 	120.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Reimplante dentário com contenção";	$p->field_valor['und'][0]['value'] = 	43.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remoção de dentes erupcionados";	$p->field_valor['und'][0]['value'] = 	90.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remoção de dreno extraoral";	$p->field_valor['und'][0]['value'] = 	50.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remoção de dreno intraoral";	$p->field_valor['und'][0]['value'] = 	50.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração temporária/tratamento expectante";	$p->field_valor['und'][0]['value'] = 	70.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Retratamento endodôntico birradicular";	$p->field_valor['und'][0]['value'] = 	450.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Retratamento endodôntico multirradicular";	$p->field_valor['und'][0]['value'] = 	550.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Retratamento endodôntico unirradicular";	$p->field_valor['und'][0]['value'] = 	380.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Sutura de ferida em região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	43.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Teste de fluxo salivar";	$p->field_valor['und'][0]['value'] = 	0.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Teste de pH salivar";	$p->field_valor['und'][0]['value'] = 	0.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento de alveolite";	$p->field_valor['und'][0]['value'] = 	43.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento de pericoronarite";	$p->field_valor['und'][0]['value'] = 	43.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento endodôntico birradicular";	$p->field_valor['und'][0]['value'] = 	350.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento endodôntico multirradicular";	$p->field_valor['und'][0]['value'] = 	450.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento endodôntico unirradicular";	$p->field_valor['und'][0]['value'] = 	280.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Cirurgia de remoção de mucocele";	$p->field_valor['und'][0]['value'] = 	290.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Consulta. profilaxia e aplicação de flúor";	$p->field_valor['und'][0]['value'] = 	120.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Controle de biofilme (placa bacteriana)";	$p->field_valor['und'][0]['value'] = 	50.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Radiografia interproximal - bite-wing";	$p->field_valor['und'][0]['value'] = 	20.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Clareamento caseiro";	$p->field_valor['und'][0]['value'] = 	300.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa 3/4 ou 4/5";	$p->field_valor['und'][0]['value'] = 	444.44;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa Veneer";	$p->field_valor['und'][0]['value'] = 	783.74;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa sobre implante";	$p->field_valor['und'][0]['value'] = 	900.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa total acrílica prensada";	$p->field_valor['und'][0]['value'] = 	358.60;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa total em cerâmica pura";	$p->field_valor['und'][0]['value'] = 	800.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa total em cerômero";	$p->field_valor['und'][0]['value'] = 	500.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa total metalocerâmica";	$p->field_valor['und'][0]['value'] = 	630.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa total metaloplástica - cerômero";	$p->field_valor['und'][0]['value'] = 	850.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa total metaloplástica - resina acrílica";	$p->field_valor['und'][0]['value'] = 	783.74;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Faceta em cerômero";	$p->field_valor['und'][0]['value'] = 	829.56;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Jig ou front plato - órtese reposicionadora";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Laminado em resina";	$p->field_valor['und'][0]['value'] = 	300.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Lentes de porcelana";	$p->field_valor['und'][0]['value'] = 	1200.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Núcleo de preenchimento";	$p->field_valor['und'][0]['value'] = 	200.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Onlay de Resina Direta";	$p->field_valor['und'][0]['value'] = 	300.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Pino de fibra de vidro";	$p->field_valor['und'][0]['value'] = 	200.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Pino pré-fabricado";	$p->field_valor['und'][0]['value'] = 	234.27;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Provisório para restauração metálica fundida";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Provisório sobre implante (Consultório)";	$p->field_valor['und'][0]['value'] = 	200.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Provisório sobre implante (Laboratório)";	$p->field_valor['und'][0]['value'] = 	600.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese fixa adesiva em cerômero livre de metal (metal free)";	$p->field_valor['und'][0]['value'] = 	1500.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese fixa adesiva indireta em metalocerâmica";	$p->field_valor['und'][0]['value'] = 	1307.99;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese fixa adesiva indireta em metaloplástica";	$p->field_valor['und'][0]['value'] = 	1046.39;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese parcial fixa In Ceran livre de metal (metal free)";	$p->field_valor['und'][0]['value'] = 	1089.33;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese parcial fixa em cerômero livre de metal (metal free)";	$p->field_valor['und'][0]['value'] = 	850.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese parcial fixa em metalocerâmica";	$p->field_valor['und'][0]['value'] = 	1237.85;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese parcial fixa em metaloplástica";	$p->field_valor['und'][0]['value'] = 	711.21;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese parcial fixa provisória (acima de três elementos)";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese parcial removível com encaixes de precisão ou de semiprecisão";	$p->field_valor['und'][0]['value'] = 	700.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese parcial removível com grampos bilateral";	$p->field_valor['und'][0]['value'] = 	650.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese sobre implante";	$p->field_valor['und'][0]['value'] = 	900.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese total de dente importado";	$p->field_valor['und'][0]['value'] = 	700.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese total imediata";	$p->field_valor['und'][0]['value'] = 	944.88;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese total incolor";	$p->field_valor['und'][0]['value'] = 	1279.65;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Reconstrução com pino de fibra de vidro";	$p->field_valor['und'][0]['value'] = 	250.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Reconstrução sem pino";	$p->field_valor['und'][0]['value'] = 	100.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Reembasamento de prótese total ou parcial - imediato (em consultório)";	$p->field_valor['und'][0]['value'] = 	205.18;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Reembasamento de prótese total ou parcial - mediato (em laboratório)";	$p->field_valor['und'][0]['value'] = 	293.11;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração em cerâmica pura - inlay";	$p->field_valor['und'][0]['value'] = 	1053.46;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração em cerâmica pura - onlay";	$p->field_valor['und'][0]['value'] = 	1053.46;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração em cerômero - inlay";	$p->field_valor['und'][0]['value'] = 	829.56;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração em cerômero - onlay";	$p->field_valor['und'][0]['value'] = 	829.56;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração em resina (indireta) - inlay";	$p->field_valor['und'][0]['value'] = 	800.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração metálica fundida";	$p->field_valor['und'][0]['value'] = 	444.44;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "órtese miorrelaxante (placa oclusal estabilizadora)";	$p->field_valor['und'][0]['value'] = 	500.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Acompanhamento de tratamento/procedimento cirúrgico em odontologia";	$p->field_valor['und'][0]['value'] = 	57.30;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Aumento de coroa clínica";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Cirurgia odontológica a retalho";	$p->field_valor['und'][0]['value'] = 	87.49;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Cirurgia periodontal a retalho";	$p->field_valor['und'][0]['value'] = 	300.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Consulta de especialista em Periodontia";	$p->field_valor['und'][0]['value'] = 	60.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Consulta e raspagem subgengival com polimento radicular";	$p->field_valor['und'][0]['value'] = 	180.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Consulta e raspagem supragengival (manual e/ou ultrassom) com profilaxia";	$p->field_valor['und'][0]['value'] = 	120.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Dessensibilização dentária";	$p->field_valor['und'][0]['value'] = 	18.46;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Enxerto conjuntivo subepitelial";	$p->field_valor['und'][0]['value'] = 	180.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Enxerto gengival livre";	$p->field_valor['und'][0]['value'] = 	135.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Enxerto pediculado";	$p->field_valor['und'][0]['value'] = 	135.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Gengivectomia";	$p->field_valor['und'][0]['value'] = 	100.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Gengivoplastia";	$p->field_valor['und'][0]['value'] = 	600.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Imobilização dentária em dentes decíduos";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Imobilização dentária em dentes permanentes";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Manutenção periodontal";	$p->field_valor['und'][0]['value'] = 	120.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remoção dos fatores de retenção do biofilme dental (placa bacteriana)";	$p->field_valor['und'][0]['value'] = 	100.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Sepultamento radicular";	$p->field_valor['und'][0]['value'] = 	142.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento de abscesso periodontal agudo";	$p->field_valor['und'][0]['value'] = 	57.42;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento de gengivite necrosante aguda - GUNA";	$p->field_valor['und'][0]['value'] = 	76.47;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tunelização";	$p->field_valor['und'][0]['value'] = 	200.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Consulta com especialista Ortodontia";	$p->field_valor['und'][0]['value'] = 	50.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Kit de documentação ortodôntica";	$p->field_valor['und'][0]['value'] = 	100.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Manutenção apa metálico + Clínico >  350.00";	$p->field_valor['und'][0]['value'] = 	98.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Manutenção apa metálico + Clínico <  200.00";	$p->field_valor['und'][0]['value'] = 	79.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Manutenção apa metálico + Clínico <  350.00";	$p->field_valor['und'][0]['value'] = 	89.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Pacote promocional Ortodontia";	$p->field_valor['und'][0]['value'] = 	80.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remoção de aparelho ortodôntico";	$p->field_valor['und'][0]['value'] = 	60.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Reposição de bracket (Valor por dente)";	$p->field_valor['und'][0]['value'] = 	18.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Aplicação de selante de fóssulas e fissuras";	$p->field_valor['und'][0]['value'] = 	50.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Aplicação de selante técnica invasiva";	$p->field_valor['und'][0]['value'] = 	65.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Condicionamento em odontologia";	$p->field_valor['und'][0]['value'] = 	29.16;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Condicionamento em odontologia para pacientes com necessidades especiais";	$p->field_valor['und'][0]['value'] = 	29.16;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Controle de cárie incipiente";	$p->field_valor['und'][0]['value'] = 	19.83;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa de acetato em dente decíduo";	$p->field_valor['und'][0]['value'] = 	100.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa de acetato em dente permanente";	$p->field_valor['und'][0]['value'] = 	100.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa de aço em dente decíduo";	$p->field_valor['und'][0]['value'] = 	300.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa de aço em dente permanente";	$p->field_valor['und'][0]['value'] = 	300.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa de policarbonato em dente decíduo";	$p->field_valor['und'][0]['value'] = 	300.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coroa de policarbonato em dente permanente";	$p->field_valor['und'][0]['value'] = 	300.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Estabilização de paciente por meio de contenção física e/ou mecânica";	$p->field_valor['und'][0]['value'] = 	29.16;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Estabilização por meio de contenção física e/ou mecânica em pacientes com necessidades especiais em odontologia";	$p->field_valor['und'][0]['value'] = 	29.16;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Mantenedor de espaço fixo";	$p->field_valor['und'][0]['value'] = 	362.66;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Mantenedor de espaço removível";	$p->field_valor['und'][0]['value'] = 	362.66;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Pulpotomia em dente decíduo";	$p->field_valor['und'][0]['value'] = 	91.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remineralização";	$p->field_valor['und'][0]['value'] = 	24.92;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração atraumática em dente decíduo";	$p->field_valor['und'][0]['value'] = 	56.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração atraumática em dente permanente";	$p->field_valor['und'][0]['value'] = 	56.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento endodôntico em dente decíduo";	$p->field_valor['und'][0]['value'] = 	140.60;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Protocolo inferior (Somente implantes)";	$p->field_valor['und'][0]['value'] = 	7780.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Protocolo superior (Somente implantes)";	$p->field_valor['und'][0]['value'] = 	7780.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese definitiva sobre implantes";	$p->field_valor['und'][0]['value'] = 	4000.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Prótese provisória para protocolo";	$p->field_valor['und'][0]['value'] = 	220.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Clareamento de dente desvitalizado";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Curativo de demora em endodontia (troca de medicação)";	$p->field_valor['und'][0]['value'] = 	60.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Preparo para núcleo intrarradicular";	$p->field_valor['und'][0]['value'] = 	39.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Pulpotomia";	$p->field_valor['und'][0]['value'] = 	91.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remoção de corpo estranho intracanal";	$p->field_valor['und'][0]['value'] = 	86.50;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remoção de núcleo intrarradicular";	$p->field_valor['und'][0]['value'] = 	67.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento de perfuração endodôntica";	$p->field_valor['und'][0]['value'] = 	189.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento endodôntico de dente com rizogênese incompleta";	$p->field_valor['und'][0]['value'] = 	200.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "AVALIAÇÃO ODONTOLOGICA ";	$p->field_valor['und'][0]['value'] = 	0.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Ajuste oclusal por acréscimo";	$p->field_valor['und'][0]['value'] = 	29.16;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Ajuste oclusal por desgaste seletivo";	$p->field_valor['und'][0]['value'] = 	29.16;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Capeamento pulpar direto";	$p->field_valor['und'][0]['value'] = 	80.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Clareamento de consultório (1 Sessão)";	$p->field_valor['und'][0]['value'] = 	250.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Núcleo de preenchimento para restauração";	$p->field_valor['und'][0]['value'] = 	200.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Pacote 3 sessões de clareamento";	$p->field_valor['und'][0]['value'] = 	700.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remoção de trabalho protético";	$p->field_valor['und'][0]['value'] = 	50.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração Estética em resina";	$p->field_valor['und'][0]['value'] = 	120.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração de amálgama - 2 faces";	$p->field_valor['und'][0]['value'] = 	73.33;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração de amálgama - 3 faces";	$p->field_valor['und'][0]['value'] = 	81.80;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração de amálgama - 4 faces";	$p->field_valor['und'][0]['value'] = 	93.70;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração de pino (intradentinário)";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração em ionômero de vidro - 2 faces";	$p->field_valor['und'][0]['value'] = 	69.90;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração em ionômero de vidro - 3 faces";	$p->field_valor['und'][0]['value'] = 	81.80;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração em ionômero de vidro - 4 faces";	$p->field_valor['und'][0]['value'] = 	81.80;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração em resina fotopolimerizável - 1 face";	$p->field_valor['und'][0]['value'] = 	50.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração em resina fotopolimerizável - 2 faces";	$p->field_valor['und'][0]['value'] = 	70.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração em resina fotopolimerizável - 3 faces";	$p->field_valor['und'][0]['value'] = 	80.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauração em resina fotopolimerizável - 4 faces";	$p->field_valor['und'][0]['value'] = 	120.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauraçãodeamálgama -1 face";	$p->field_valor['und'][0]['value'] = 	57.30;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Restauraçãoemionômerodevidro- 1 face";	$p->field_valor['und'][0]['value'] = 	57.30;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Alveoloplastia";	$p->field_valor['und'][0]['value'] = 	112.35;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Amputação radicular com obturação retrógrada";	$p->field_valor['und'][0]['value'] = 	226.14;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Amputação radicular sem obturação retrógrada";	$p->field_valor['und'][0]['value'] = 	211.94;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Apicetomia birradicular com obturação retrógrada";	$p->field_valor['und'][0]['value'] = 	384.67;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Apicetomia birradicular sem obturação retrógrada";	$p->field_valor['und'][0]['value'] = 	333.50;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Apicetomia multirradicular com obturação retrógrada";	$p->field_valor['und'][0]['value'] = 	433.79;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Apicetomia multirradicular sem obturação retrógrada";	$p->field_valor['und'][0]['value'] = 	398.54;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Apicetomia unirradicular com obturação retrógrada";	$p->field_valor['und'][0]['value'] = 	348.17;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Apicetomia unirradicular sem obturação retrógrada";	$p->field_valor['und'][0]['value'] = 	303.58;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Aprofundamento/aumento de vestíbulo";	$p->field_valor['und'][0]['value'] = 	116.65;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Bichectomia (Remoção das bolas de Bichat)";	$p->field_valor['und'][0]['value'] = 	500.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Biópsia de boca";	$p->field_valor['und'][0]['value'] = 	140.42;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Biópsia de glândula salivar";	$p->field_valor['und'][0]['value'] = 	140.42;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Biópsia de lábio";	$p->field_valor['und'][0]['value'] = 	140.42;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Biópsia de língua";	$p->field_valor['und'][0]['value'] = 	140.42;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Biópsia de mandíbula";	$p->field_valor['und'][0]['value'] = 	140.42;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Biópsia de maxila";	$p->field_valor['und'][0]['value'] = 	140.42;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Bridectomia";	$p->field_valor['und'][0]['value'] = 	210.06;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Bridotomia";	$p->field_valor['und'][0]['value'] = 	210.06;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Cirurgia para exostose maxilar";	$p->field_valor['und'][0]['value'] = 	116.65;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Cirurgia para torus mandibular bilateral";	$p->field_valor['und'][0]['value'] = 	188.21;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Cirurgia para torus mandibular unilateral";	$p->field_valor['und'][0]['value'] = 	94.11;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Cirurgia para torus palatino";	$p->field_valor['und'][0]['value'] = 	116.65;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Coleta de raspado em lesões ou sítios específicos da região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	46.66;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Consulta de especialista em Estomatologia";	$p->field_valor['und'][0]['value'] = 	29.16;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Cunha proximal";	$p->field_valor['und'][0]['value'] = 	99.46;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Diagnóstico e tratamento de estomatite herpética";	$p->field_valor['und'][0]['value'] = 	29.16;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Diagnóstico e tratamento de estomatite por candidose";	$p->field_valor['und'][0]['value'] = 	29.16;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Diagnóstico e tratamento de halitose";	$p->field_valor['und'][0]['value'] = 	29.16;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Diagnóstico e tratamento de xerostomia";	$p->field_valor['und'][0]['value'] = 	29.16;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Exodontia a retalho";	$p->field_valor['und'][0]['value'] = 	90.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Exodontia de permanente por indicação ortodôntica/protética (utilizar para terceiros molares erupcionados)";	$p->field_valor['und'][0]['value'] = 	75.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Exodontia de raiz residual";	$p->field_valor['und'][0]['value'] = 	120.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Exodontia simples de permanente";	$p->field_valor['und'][0]['value'] = 	90.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Exérese de lipoma na região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	365.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Exérese ou excisão de cistos odontológicos";	$p->field_valor['und'][0]['value'] = 	219.42;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Exérese ou excisão de cálculo salivar";	$p->field_valor['und'][0]['value'] = 	186.79;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Exérese ou excisão de mucocele";	$p->field_valor['und'][0]['value'] = 	177.83;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Exérese ou excisão de rânula";	$p->field_valor['und'][0]['value'] = 	234.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Odontossecção";	$p->field_valor['und'][0]['value'] = 	142.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Punção aspirativa na região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	46.66;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Reconstrução de sulco gengivo-labial";	$p->field_valor['und'][0]['value'] = 	116.65;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Redução cruenta de fratura alvéolo-dentária";	$p->field_valor['und'][0]['value'] = 	825.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Redução de tuberosidade";	$p->field_valor['und'][0]['value'] = 	116.65;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Redução incruenta de fratura alvéolo-dentária";	$p->field_valor['und'][0]['value'] = 	700.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remoção de corpo estranho no seio maxilar";	$p->field_valor['und'][0]['value'] = 	440.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remoção de dente incluso horizontal";	$p->field_valor['und'][0]['value'] = 	250.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remoção de dentes inclusos/impactados";	$p->field_valor['und'][0]['value'] = 	200.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remoção de dentes semi-inclusos";	$p->field_valor['und'][0]['value'] = 	150.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Remoção de odontoma";	$p->field_valor['und'][0]['value'] = 	365.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tracionamento cirúrgico com finalidade ortodôntica";	$p->field_valor['und'][0]['value'] = 	373.30;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento cirúrgico das fístulas buconasais";	$p->field_valor['und'][0]['value'] = 	280.79;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento cirúrgico das fístulas bucosinusais";	$p->field_valor['und'][0]['value'] = 	280.79;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento cirúrgico de bridas constritivas da região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	210.06;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento cirúrgico de hiperplasias de tecidos moles na região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	46.66;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento cirúrgico de hiperplasias de tecidos ósseos/cartilaginosos na região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	46.66;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento cirúrgico de tumores benignos de tecidos ósseos/cartilaginosos na região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	410.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento cirúrgico dos tumores benignos de tecidos moles na região bucomaxilofacial";	$p->field_valor['und'][0]['value'] = 	365.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Tratamento cirúrgico para tumores odontogênicos benignos - sem reconstrução";	$p->field_valor['und'][0]['value'] = 	470.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Ulectomia";	$p->field_valor['und'][0]['value'] = 	70.00;$n = node_submit($p);$salvo = node_save($n);
  $p = new stdClass();$p->uid = 1;$p->language = 'pt-br';$p->status = 1;$p->field_categoria['und'][0]['tid'] = 1;$p->type = "procedimento";$p->title = "Ulotomia";	$p->field_valor['und'][0]['value'] = 	60.00;$n = node_submit($p);$salvo = node_save($n);
  */
  // $n = node_submit($p);
  // $salvo = node_save($n);


}

function salvarProntuario(){
  
  global $user;
  global $base_url;

  $agendamento = node_load($_POST['agendamento']);

  $prontuario                     = new stdClass();
  $prontuario->title              = "Prontuário ".time();
  $prontuario->uid                = $user->uid;
  $prontuario->language           = 'pt-br';
  $prontuario->status             = 1;
  $prontuario->type               = 'prontuario';
  $prontuario->body
  ['und'][0]['value']             = $_POST['body'];
  $prontuario->field_agendamento
  ['und'][0]['target_id']         = $agendamento->nid;
  $prontuario->field_paciente
  ['und'][0]['target_id']         = $_POST['paciente'];

  $n = node_submit($prontuario);
  $salvo = node_save($n);

  // Status de atendido
  $agendamento->field_status['und'][0]['value'] = 4;
  $n = node_submit($agendamento);
  $salvo = node_save($n);

  header('Location: '.$base_url."/#overlay=admin/create/agendamento/".$agendamento->nid."/".$_POST['paciente']."/".$agendamento->field_profissional['und'][0]['target_id']);
  
}

function manipulaAgendamento(){
  
  // $a = node_load(63);
  // echo "<pre>";
  // print_r($a);
  // die();

  $agendamento = node_load($_POST['ID']);
  // Dados iniciais caso não exista agendamento passado como parametro
  if(!$agendamento){
    $agendamento->type = 'agendamento';
    $agendamento->language = 'pt-br';
    $agendamento->status = 1;
    $agendamento->comment = 0;
    $agendamento->promote = 0;
    $agendamento->sticky = 0;
    global $user;
    $agendamento->uid = $user->uid;
    $agendamento->title = 'Agendamento '.time();
  }
  
  // Independentemente de alteração, esses dados sempre serão alterados no node
  $agendamento->body['und'][0]['value'] = 'OBS';
  $agendamento->field_profissional['und'][0]['target_id'] = $_POST['PROFISSIONAL'];
  $agendamento->field_paciente['und'][0]['target_id'] = $_POST['PACIENTE'];
  $agendamento->field_status['und'][0]['value'] = $_POST['STATUS'];
  foreach($_POST['TIPO_DE_AGENDAMENTO'] as $k=>$v){
    $agendamento->field_tipo_de_agendamento['und'][$k]['value'] = $v;
  }

  $dt = explode('/',$_POST['DATA']);
  $dataAgendamento = $dt[2]."-".$dt[1]."-".$dt[0]." ".$_POST['HORA'].":00";
  $agendamento->field_data['und'][0]['value'] = $dataAgendamento;
  $agendamento->field_data['und'][0]['value2'] = date("Y-m-d H:i:s",strtotime('+30 minutes',strtotime($dataAgendamento)));

  // Salva o novo agendamento caso ele não exista
  if(!$agendamento->nid){
    $n = node_submit($agendamento);
    $salvo = node_save($n);
    
    $result = db_select("node","n")
    ->fields('n')
    ->condition('title',$agendamento->title)
    ->execute()
    ->fetchAssoc();
    $agendamento = node_load($result['nid']);
  }

  //Preenche esses dados e os atualiza sempre que executar este processo
  $rowIndex = ($_POST['PROCEDIMENTO']['index'])?intval($_POST['PROCEDIMENTO']['index']):intval($_POST['PAGAMENTO']['index']);

  if($_POST['PROCEDIMENTO']['action'] == 'delPro'){
    
    unset($agendamento->field_procedimentos['und'][$rowIndex]);
    unset($agendamento->field_obs_do_procedimento['und'][$rowIndex]);
    unset($agendamento->field_quantidade_do_procedimento['und'][$rowIndex]);
    unset($agendamento->field_executou['und'][$rowIndex]);
    unset($agendamento->field_valor['und'][$rowIndex]);

  } elseif($_POST['PROCEDIMENTO']['action'] == 'updPro' || $_POST['PROCEDIMENTO']['action'] == 'addPro') {

    $agendamento->field_procedimentos['und'][$rowIndex]['target_id']          = $_POST['PROCEDIMENTO']['id'];
    $agendamento->field_obs_do_procedimento['und'][$rowIndex]['value']        = $_POST['PROCEDIMENTO']['Detalhes'];
    $agendamento->field_quantidade_do_procedimento['und'][$rowIndex]['value'] = $_POST['PROCEDIMENTO']['QTD'];
    $agendamento->field_executou['und'][$rowIndex]['value']                   = ($_POST['PROCEDIMENTO']['Executou'] == 'false')? 0:1;
    $agendamento->field_valor['und'][$rowIndex]['value']                      = $_POST['PROCEDIMENTO']['Valor'];

  } elseif($_POST['PAGAMENTO']['action'] == 'delPag'){
    
    unset($agendamento->field_valor_pago['und'][$rowIndex]);
    unset($agendamento->field_forma['und'][$rowIndex]);
    unset($agendamento->field_parcelas['und'][$rowIndex]);
    unset($agendamento->field_data_do_pagamento['und'][$rowIndex]);

  } elseif($_POST['PAGAMENTO']['action'] == 'updPag' || $_POST['PAGAMENTO']['action'] == 'addPag'){
    
    $agendamento->field_valor_pago['und'][$rowIndex]['value']         = $_POST['PAGAMENTO']['ValorPgto'];
    $agendamento->field_forma['und'][$rowIndex]['value']              = $_POST['PAGAMENTO']['FormaPgto'];
    $agendamento->field_parcelas['und'][$rowIndex]['value']           = $_POST['PAGAMENTO']['Parcelas'];
    
    $dataPgto = str_replace('T',' ',$_POST['PAGAMENTO']['DataPgto']);
    $dataPgto = substr($dataPgto, 0, -5);
    $agendamento->field_data_do_pagamento['und'][$rowIndex]['value']  = $dataPgto;

  }
  // print_r($agendamento); die();
  // Atualiza todo o agendamento
  $n = node_submit($agendamento);
  $salvo = node_save($n);
  echo $agendamento->nid;
  
}

function paciente_form($form, &$form_state) {
  $aredirect = explode('/',$_GET['q']);
  $profissional = $aredirect[count($aredirect)-1];
  $redirect = $aredirect[count($aredirect)-2].'/'.$profissional;
  
  $form['nome'] = array(
    '#type' => 'textfield', 
    '#autocomplete_path' => 'entityreference/autocomplete/single/field_paciente/node/agendamento/NULL',
    '#title' => 'Nome do paciente',
    '#id' => 'autocompleteNomePaciente',
    '#size' => 60,
    '#maxlength' => 255,
    '#required' => false,
  );
  $form['telefone'] = array(
    '#type' => 'textfield',
    '#title' => 'Telefone',
    '#size' => 20,
    '#maxlength' => 17,
    '#required' => false, 
  );
  $form['redirect'] = array(
    '#type' => 'hidden', 
    '#size' => 60,
    '#maxlength' => 255,
    '#id' => 'redirect',
    '#value' => $redirect,
    '#required' => false,
  );
  $form['uid'] = array(
    '#type' => 'hidden', 
    '#size' => 60,
    '#maxlength' => 255,
    '#id' => 'uid',
    '#required' => false,
  );
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => 'Salvar e continuar...',
  );
  $form['#attached']['js'] = array(
    drupal_get_path('module', 'eventos') . '/includes/js/forms.js',
  );

  drupal_add_js(path_to_theme().'/js/utils.js');
  return $form;
}

function retiraAcentos($string){
  $acentos  =  'ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûýýþÿŔŕ';
  $sem_acentos  =  'aaaaaaaceeeeiiiidnoooooouuuuybsaaaaaaaceeeeiiiidnoooooouuuyybyRr';
  $string = strtr($string, utf8_decode($acentos), $sem_acentos);
  $string = str_replace(" ","-",$string);
  return utf8_decode($string);
}

function paciente_form_validate($form, &$form_state) {
    
  if($form['uid']['#value'] == ' '|| $form['uid']['#value'] == ''){
    $erroNome = preg_match('|^[\pL\s]+$|u',$form['nome']['#value']);
    if(!$erroNome){
      form_set_error('nome', "Nome do paciente inválido ".$erroNome);
    }
    
  }

  $erro = db_select("users","u")
    ->fields('u')
    ->condition('name',$form['nome']['#value'])
    ->execute()
    ->fetchAssoc();
  
  if($erro){
    form_set_error('nome', t('Tivemos um problema ao cadastrar esse paciente, troque o nome e tente novamente'));
  }

}

function paciente_form_submit($form, &$form_state) {

  $n = array();
  $n = explode(' - ',$form['nome']['#value']);
  $nomeCompleto = (count($n) > 0)?$n[0]:$form['nome']['#value'];
  $nomeCompletoSemAcento = retiraAcentos($nomeCompleto);

  $name = trim($nomeCompletoSemAcento, " \t\n\r");
  $email = ($nomeCompleto == '')?null:$name.rand()."@nesaude.com";

  $telefone = array(
    'und' => array(
      0 => array(
        'value' => $form['telefone']['#value'],
        'format' => '',
        'safe_value' => $form['telefone']['#value']
      )
    )
  );

  $new_user = array(
    'name' => $email,
    'pass' => '$S$DdZ32sNE2leF3STLsNGgr5ywhHRQQ7MblpezVAc2VFK7valrkr5R', // senha
    'mail' => $email,
    'status' => 1,
    'init' => $email,
    'roles' => array(
      DRUPAL_AUTHENTICATED_RID => 'authenticated user',
      5 => 'Paciente'
    ),
    'field_nome_completo' => array(
      'und' => array(
        0 => array(
          'value' => $nomeCompleto,
          'format' => '',
          'safe_value' => $nomeCompletoSemAcento
        )
      )
    ),
    'field_telefone' => $telefone
  );
  
  $uid = $form['uid']['#value'];

  if($uid == ' ' || $uid == ''){
 
    $account = user_save('',$new_user);
    $usr = user_load_by_mail($email);
    $uid = $usr->uid;
    
  } else {

    $usr = user_load($uid);
    $edit = array('field_telefone' => $telefone);
    $account = user_save($usr,$edit);

  }
  
  if (!$account) {

    drupal_set_message(t("Erro ao salvar o Paciente."), 'error');
    $form_state['redirect'] = '';
    return;

  } else {
    
    $uid = $usr->uid;
    $profissional = explode('/',$form['redirect']['#value']);
    $url = '/admin/create/agendamento/'.$uid.'/'.$profissional[1];

    $form_state['redirect'] = url($url, array('absolute' => true));
    
  }

}

function getEventos(){

  global $user;
  if(isset($user->roles[4]) && !isset($user->roles[3])){

    $_GET['uid'] = $user->uid;
    getEventosByProfissional();

  } else {

    $dtInicial = str_replace("T"," ",$_GET['start']);
    $dtFinal = str_replace("T"," ",$_GET['end']);

    $sql = "
    SELECT nid FROM node as n

    INNER JOIN field_data_field_data as d
    ON n.nid = d.entity_id
    
    WHERE 
      type = 'agendamento'
    AND
      d.field_data_value > '$dtInicial'
    AND 
      d.field_data_value2 < '$dtFinal'
    "; 
    
    $event = Array();
    $event = processaEventos($sql,'ALL');

    $retorno = json_encode($event);
    print($retorno);

  }

}

function getEventosByProfissional(){
  
  global $user;
  if(isset($user->roles[4]) && !isset($user->roles[3])){

    $_GET['uid'] = $user->uid;

  }
 
  $start = str_replace("T"," ",$_GET['start']);
  $end = str_replace("T"," ",$_GET['end']);
  $uid = $_GET['uid'];

  $sql = "
  SELECT nid FROM node as n

  INNER JOIN field_data_field_data as d
  ON n.nid = d.entity_id
  
  INNER JOIN field_data_field_profissional as p
  ON n.nid = p.entity_id
  
  WHERE 
    type = 'agendamento'
  AND
    d.field_data_value > '$start'
  AND 
    d.field_data_value2 < '$end'
  AND
    p.field_profissional_target_id = $uid
  "; 
  
  $event = Array();
  $event = processaEventos($sql,'individual');

  $retorno = json_encode($event);

  print_r($retorno);
  
}

function processaEventos($sql,$tipo){

  $event = Array();
  $procedimentos = Array();
  $classNames = Array();
  array_push($classNames,'evento');
  $result = db_query($sql);
  foreach($result as $row){
    
    
    $agendamento = node_load($row->nid);
    
    $paciente = user_load($agendamento->field_paciente['und'][0]['target_id']);
    $title = $paciente->field_nome_completo['und'][0]['safe_value'];
    
    $profissional = user_load($agendamento->field_profissional['und'][0]['target_id']);
    
      switch ($agendamento->field_status['und'][0]['value']) {
        case 0:
          $classNames = "Agendado";
          $borderColor = "#CCCCCC";
          break;
        case 1:
          $classNames = "Confirmado";
          $borderColor = "#00FF00";
        break;
        case 2:
          $classNames = "Emespera";
          $borderColor = "#FF8C00";
        break;
        case 3:
          $classNames = "Ematendimento";
          $borderColor = "#8B008B";
        break;
        case 4:
          $classNames = "Atendido";
          $borderColor = "#6495ED";
        break;
        case 5:
          $classNames = "Cancelado";
          $borderColor = "#FF0000";
          break;                        
        default:
          $classNames = "evento";
          $borderColor = $profissional->field_cor['und'][0]['rgb'];
          break;
      }
      $cor = $profissional->field_cor['und'][0]['rgb'];
    
    if(count($agendamento->field_procedimentos) > 0){
      foreach($agendamento->field_procedimentos['und'] as $procedimento){

        $objProc = new stdClass();
        $objProc->procedimento = $procedimento['target_id'];
        array_push($procedimentos,$objProc);
  
      }
    }
    
    
    $start = str_replace(" ","T",$agendamento->field_data['und'][0]['value']);
    $end = str_replace(" ","T",$agendamento->field_data['und'][0]['value2']);

    $objEvt                 = new stdClass();
    $objEvt->id             = $agendamento->nid;
    $objEvt->title          = $title;
    $objEvt->start          = $start;
    $objEvt->end            = $end;
    $objEvt->color          = $cor;
    $objEvt->borderColor    = $borderColor;
    $objEvt->classNames     = $classNames;
    $objEvt->url            = "#overlay=admin/create/agendamento/$row->nid/".$agendamento->field_paciente['und'][0]['target_id']."/$profissional->uid";
    
    array_push($event,$objEvt);
    
  }

  return $event;

}

function alterEvento(){
  $agendamento = node_load($_POST['id']);
  
  $agendamento->field_data['und'][0]['value'] = $_POST['start'];
  $agendamento->field_data['und'][0]['value2'] = $_POST['end'];

  $n = node_submit($agendamento);
  $ret = node_save($n);
  print_r($ret);

}

function getProcedimentos(){
  
  $nid = '';
  $ret = Array();
  $objProcedimento[] = new stdClass();
  $valorTotal = 0;

  if(!isset($_GET['nid'])){
    return '[]';
  } else {
    $nid = $_GET['nid'];
  }

  $agendamento = node_load($nid);
  foreach($agendamento->field_procedimentos['und'] as $k=>$v){

    $proc = node_load($v['target_id']);

    $objProcedimento[$k]->id            = $v['target_id'];
    $objProcedimento[$k]->Procedimento  = $proc->title;
    $objProcedimento[$k]->QTD           = $agendamento->field_quantidade_do_procedimento['und'][$k]['value'];
    $objProcedimento[$k]->Valor         = floatval($agendamento->field_valor['und'][$k]['value']);
    $objProcedimento[$k]->Detalhes      = $agendamento->field_obs_do_procedimento['und'][$k]['value'];
    $objProcedimento[$k]->Executou      = boolval($agendamento->field_executou['und'][$k]['value']);
    
    $valorTotal += $objProcedimento[$k]->Valor;
    $objProcedimento[$k]->Total         = $valorTotal;
    
    array_push($ret,$objProcedimento[$k]);
  }
  
  print(json_encode($ret));

}

function getDadosProcedimentos(){

  $procedimento = node_load($_GET['nid']);

  print(json_encode($procedimento));

}

function getPagamentos(){

  $nid = '';
  $ret = Array();
  $objPagamento[] = new stdClass();
  $valorTotal = 0;

  if(!isset($_GET['nid'])){
    return '[]';
  } else {
    $nid = $_GET['nid'];
  }

  $agendamento = node_load($nid);
  foreach($agendamento->field_forma['und'] as $k=>$v){
    unset($agendamento->field_valor_pago['und'][$rowIndex]);
    unset($agendamento->field_forma['und'][$rowIndex]);
    unset($agendamento->field_parcelas['und'][$rowIndex]);
    unset($agendamento->field_data_do_pagamento['und'][$rowIndex]);

    // $objPagamento[$k]->id         = $k;
    $objPagamento[$k]->valorPgto  = floatval($agendamento->field_valor_pago['und'][$k]['value']);
    $objPagamento[$k]->formaPgto  = intval($agendamento->field_forma['und'][$k]['value']);
    $objPagamento[$k]->parcelas   = $agendamento->field_parcelas['und'][$k]['value'];

    $dt = explode(" ",$agendamento->field_data_do_pagamento['und'][$k]['value']);
    $dt = explode('-',$dt[0]);
    $objPagamento[$k]->dataPgto   = $dt[2].'/'.$dt[1].'/'.$dt[0];
    
    $valorTotal += $objPagamento[$k]->valorPgto;
    $objPagamento[$k]->Total         = $valorTotal;
    
    array_push($ret,$objPagamento[$k]);
  }
  
  print(json_encode($ret));

}

function getCalculo($agendamentoId,$retorno,$tipo){
  
  $agendamento = node_load($agendamentoId);

  if($tipo == 'pago'){
    if(isset($agendamento->field_valor_pago['und'])){
      foreach($agendamento->field_valor_pago['und'] as $k=>$v){
        $retorno += floatval($v['value']);
      }
    }
  } elseif($tipo == 'executado'){
    if(isset($agendamento->field_procedimentos['und'])){
      foreach($agendamento->field_procedimentos['und'] as $k=>$v){
        if($agendamento->field_executou['und'][$k]['value']){
          $retorno += floatval($agendamento->field_valor['und'][$k]['value']);
        }
      }
    }  
  }

  return $retorno;
}

function getSaldo(){
  
  $totalExecutado  = 0.00;
  $totalPago  = 0.00;
  $ret = Array();
  $objSaldo = new stdClass();

  if(isset($_GET['pid'])){
    // Recupera o saldo por PACIENTE
    $pid = $_GET['pid'];
    $sql = "
      SELECT nid FROM node as n

      INNER JOIN field_data_field_paciente as pid
      ON n.nid = pid.entity_id

      WHERE pid.field_paciente_target_id = $pid
      "; 
  } elseif(isset($_GET['uid'])){
    // Para relatório de produtividade por período
    $uid = intval($_GET['uid']);
    $sql = "
      SELECT nid FROM node as n

      INNER JOIN field_data_field_data as d
      ON n.nid = d.entity_id
      
      INNER JOIN field_data_field_profissional as p
      ON n.nid = p.entity_id
      
      WHERE 
        type = 'agendamento'
      "; 

    if(isset($_GET['start']) && isset($_GET['end'])){

      $start = $_GET['start'];
      $end = $_GET['end'];
      $sql .= "
      AND
        d.field_data_value 
      BETWEEN 
      '$start'
      AND
      '$end'
      AND
        p.field_profissional_target_id = $uid
      
      ";
    }
    //debugFake($sql);
  } else {
    die(0.00);
  }

  
  $event = Array();
  $result = db_query($sql); 

  foreach($result as $row){
    
    if(isset($_GET['nid']) && $row->nid == $_GET['nid']){
      // Separa os pagamentos por agendamento
      $totalPago      = getCalculo($row->nid,$totalPago,'pago');
      $totalExecutado = getCalculo($row->nid,$totalExecutado,'executado');
    } elseif(!isset($_GET['nid'])) {
      // Consolida valores totais, sem separação por agendamento
      $totalPago      = getCalculo($row->nid,$totalPago,'pago');
      $totalExecutado = getCalculo($row->nid,$totalExecutado,'executado');
    }
  }

  $objSaldo->totalPago      = $totalPago;
  $objSaldo->totalExecutado = $totalExecutado;

  array_push($ret,$objSaldo);

  print(json_encode($ret));
  
}

function debugFake($p){
  echo "<pre>";
    print_r($p);
  echo "<pre>";
  die();
}
